### ISSUE TITLE
Crashing loading into the World Update 4

### ISSUE THREAD

**Issue by AF1134** [Sequal32/yourcontrolsinstaller#1]
Hello,

The mod in the comunity folder make the loading crash.
Hope you will fix it soon. I love your mod.
How to unistall it ?

Thanks for reply
Franck

**Comment by Sequal32** [comment]
Unfortunately there's nothing I can do about it. The update caused all addons/mods that use standalone WASM modules to crash the sim when loading in. We have to wait for a hotfix from Asobo.
